// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Playback   = require("playback");
var DiscordRpc = require("discord-rpc");

var appClient = "395127794029428736";

var appImage = "itunes_logo_large";

var rpc = new DiscordRpc.Client({
      transport: "ipc"
    });

rpc.login(appClient);

function onReady() {
  Playback.on("playing", (function (data) {
          var song = data.name;
          var artist = data.artist;
          return rpc.setActivity({
                      details: "🎵 Listening to",
                      state: "" + (String(song) + (" by " + (String(artist) + " "))),
                      largeImageKey: appImage
                    });
        }));
  Playback.on("paused", (function (data) {
          var song = data.name;
          var artist = data.artist;
          return rpc.setActivity({
                      details: "Paused...",
                      state: "" + (String(song) + (" by " + (String(artist) + " "))),
                      largeImageKey: appImage
                    });
        }));
  return /* () */0;
}

rpc.on("ready", onReady);

exports.appClient = appClient;
exports.appImage  = appImage;
exports.rpc       = rpc;
exports.onReady   = onReady;
/* rpc Not a pure module */
